# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('ser_name', models.CharField(max_length=20)),
                ('ser_passwd', models.CharField(max_length=16)),
                ('grant_host', models.CharField(max_length=20)),
                ('dbname', models.CharField(max_length=32)),
                ('dbprivileges', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=50)),
            ],
        ),
    ]
