# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0002_auto_20170915_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='userinfo',
            new_name='dbuserinfo',
        ),
    ]
