# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0003_auto_20170915_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuserinfo',
            name='dbname',
            field=models.CharField(max_length=32, verbose_name='DBNAME'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='dbprivileges',
            field=models.CharField(max_length=30, verbose_name='DB\u6388\u6743\u8be6\u60c5'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='grant_host',
            field=models.CharField(max_length=20, verbose_name='DB\u6388\u6743IP/IP\u7f51\u6bb5'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='ser_name',
            field=models.CharField(max_length=20, verbose_name='DB\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='ser_passwd',
            field=models.CharField(max_length=16, verbose_name='DB\u7528\u6237\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='user_name',
            field=models.CharField(max_length=50, verbose_name='DB\u5bf9\u63a5\u4eba'),
        ),
    ]
