# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0004_auto_20170915_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuserinfo',
            name='adduser',
            field=models.CharField(max_length=20, null=True, verbose_name='\u6dfb\u52a0\u4eba'),
        ),
        migrations.AddField(
            model_name='dbuserinfo',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
