# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0005_auto_20170916_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbuserinfo',
            name='dbhost',
            field=models.CharField(max_length=20, null=True, verbose_name='\u6570\u636e\u5e93IP'),
        ),
    ]
