# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0006_dbuserinfo_dbhost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbuserinfo',
            name='comment',
            field=models.CharField(max_length=50, verbose_name='\u9884\u53d1\u5e03or\u751f\u4ea7'),
        ),
    ]
