# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-15 16:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0008_auto_20170916_0023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbuserinfo',
            options={'verbose_name': 'DB\u7528\u6237\u8bb0\u5f55\u8868', 'verbose_name_plural': 'DB\u7528\u6237\u8868'},
        ),
    ]
