# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0009_auto_20170916_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_project_name', models.CharField(max_length=30, verbose_name='\u9879\u76ee\u540d\u5b57')),
                ('t_owner', models.CharField(max_length=20, verbose_name='\u9879\u76ee\u8d1f\u8d23\u4eba')),
                ('t_dbhost', models.CharField(max_length=20, verbose_name='\u6570\u636e\u5e93IP')),
                ('t_rootpasswd', models.CharField(max_length=20, verbose_name='root\u7528\u6237\u5bc6\u7801')),
                ('t_dbs', models.CharField(max_length=64, verbose_name='\u6240\u542b\u6570\u636e\u5e93')),
                ('t_createuser', models.CharField(max_length=32, verbose_name='\u6dfb\u52a0\u4eba')),
                ('t_createtime', models.DateTimeField(auto_now_add=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('t_updatetime', models.DateTimeField(auto_now=True, verbose_name='\u66f4\u6539\u65f6\u95f4')),
                ('t_comment', models.CharField(max_length=64, verbose_name='\u6ce8\u91ca')),
            ],
            options={
                'verbose_name': '\u751f\u4ea7\u6570\u636e\u5e93\u7edf\u8ba1\u8868',
                'verbose_name_plural': '\u751f\u4ea7\u6570\u636e\u5e93\u4fe1\u606f\u7edf\u8ba1\u8868',
            },
        ),
        migrations.AlterModelOptions(
            name='dbuserinfo',
            options={'verbose_name': '\u751f\u4ea7\u6570\u636e\u5e93\u7528\u6237\u7edf\u8ba1\u8868', 'verbose_name_plural': '\u751f\u4ea7\u6570\u636e\u5e93\u5e94\u7528\u7528\u6237\u8868'},
        ),
    ]
