# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0010_auto_20170919_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbuserinfo',
            options={'verbose_name': '\u5e94\u7528\u7528\u6237\u8868', 'verbose_name_plural': '\u5e94\u7528\u7528\u6237\u8868'},
        ),
        migrations.AlterField(
            model_name='dbuserinfo',
            name='ser_passwd',
            field=models.CharField(max_length=100, verbose_name='DB\u7528\u6237\u5bc6\u7801'),
        ),
    ]
