# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-19 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbopsModel', '0011_auto_20170919_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='t_rootpasswd',
            field=models.CharField(max_length=100, verbose_name='root\u7528\u6237\u5bc6\u7801'),
        ),
    ]
